# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Trail.create!(trail_forks_id: 64411, name: 'Cadillac River Runner', description: 'This is a cross country-style trail that also utilizes the bow river pathway to link up sections, and is best ridden at low water.', length: 3300, difficulty: 3, coded_path: "{mqvH`_kwT[kCJc@Eu@}@aD]a@KYUOYu@Uc@UUo@aE_AmDGo@i@uC_@yAg@aBe@uD_@}B[gAiBoEa@sAGa@JIvEoBBQQ}As@e@Sq@c@gAe@uBm@cAm@gBkBqDuB_Fn@uBa@uCBs@UiBkB`@LvAVl@BrAcBqAm@cAuAiEeCkHu@uDb@Us@qASw@I}@[`@WwC[qB]iDXoCMuALsDXiBdA\d@eBFkBb@aBdBgBjAgAvAiAv@a@vAkBVtAo@jBeA|Ao@zBo@tCDf@lBL")

Trail.create!(trail_forks_id: 156216, name: 'Regional Pathway - Edworthy to Inglewood', description: 'This section of the regional pathway connects Edworthy Park to Inglewood along the north side of the Bow River.', length: '13402.4', difficulty: 1, coded_path: 'ertvH`ovwTl@eAzIyIhB_BxC_DzEqEfB}AlBkBlBwBzBoCz@oA`AeCVoAtAyOJuAH{DPmBPeENq@AkBEaADgMTeCVcBFoAx@}EtAqHn@}Br@eEp@iE@m@RkBf@kCBWx@_CnAoF^mBnAgEtCgIvDeJfAwBt@oA|@_AZW~Aw@vC{@`Ae@r@m@p@}@~AoCRi@d@oCLe@Hm@@iCOkBEuCSaD[oAWcBEyA_A{FOq@WyBe@qAGWOcD?yTh@eQFqCByEC{CMeCCyHLqIFcA?e@QiBM][k@}BqDaAcBuAgB_@gAWuAmBkOASBSZmABW?q@W{Bm@wD[gAe@gAY_Ai@gAK[Uw@a@iCcAsDe@iA_DkGgCmFyFsKo@}AqCeFg@wAq@_DKu@MaB_@{GMeEBaEEU?k@\oNHoAt@cDbAgCt@sAtAaB\WtCyClAq@zA}An@c@JQPMLSPg@`@mCFm@AQ^gBFc@jByJXq@lCyN\oC`@yAVqAXyBTeAbAgD\sAr@eAXiARoBbA{E@QCW@[dAwHCaA@WH[LoAb@mCFk@NkDJuAZqCD{A?{KBaBFkAHk@JWFC\sBHeAPiAfBqH^qBNaBPeDNyEXqFHo@b@sB`@uE`@aDEm@Bk@`@kEB}BLi@tBqFXe@rA{AVu@\sAd@gATs@x@uEXwCHmC@m@KyAWaAmBeEOiAA}AE[y@e@g@Bi@LaFXg@LOLKyBdD]bEIb@IRg@PkC@cEOkASe@ESLg@A_@KQ_@UCM@K\{@TkADe@Ew@AkANyAToAz@cCHs@bAyCvBwF|A_DfBqCtBeBfAo@pC{@bBm@VDd@f@bAdBr@`AvC|B\HxFvLH@TOJQJIaAtNAh@QlBE@@aBIoA')


Trail.create!(trail_forks_id: 156458, name: 'Regional Pathway - Ogden to Inglewood', description: 'Paved pathway along the Bow River that access [L=https://www.trailforks.com/trails/pearce-estate/] Pearce Estate[/L] Park and Inglewood Bird Sanctuary, among other sites.', length: '7589.83', difficulty: 1, coded_path: '{ugvHd|zvT?OkA{CaAyBWCc@FyFpFy@n@_Al@gCbAq@RaDp@sBDiCOw@M{D_AUAOJMW_Bc@MXw@c@aEeAk@E_@GQQKEUQ_AUgB[}@GwDCoBl@mAr@}@|@_@P_@f@sEpICc@Qe@uCuCeA{@QIM?_@Ja@u@U@c@ZeAVk@Xg@b@o@Hg@VcBAg@Gq@Ju@IsAZ{CGmBH_A?yAQgJaD{D}A}D]cBEuMCm@Ow@EgFCmG@eDF_E^gA\OIqA_BOBGHC^yAhE_AdCIFCVsBfF_@_@WIUJq@dAE?y@}@MGcFFiCCcCs@WJg@Mg@[qAcAqAwA_AoAi@a@_BUmAc@wA`@Ih@c@Ng@z@gAf@iBdCo@ZOVg@lBkAfDk@zBYxBK|CE`@a@dAMd@Iz@Bf@?|@Xv@t@|EJ^j@h@nA~I|AdK\pADr@xD@b@j@Hx@ErB@LAvAG~BOdA[vD_@jCMl@Uf@qAhBu@^QVe@ZU|@Q~Co@hCOXK\SbCWhAm@bDQf@If@At@_@vC[`DeAlFw@jEm@pEI~@?f@HZr@pBFf@')


Trail.create!(trail_forks_id: 153372, name: 'Fort Calgary To Edworthy Park', description: 'This family-friendly paved path along the south side of the Bow River past downtown Calgary is part of the City of Calgary"s multi-use pathway system and is also a segment of The Great Trail (Sentier Transcanadien) network.   The east end of this segment starts at a pedestrian bridge at Fort Calgary on the south bank of the Bow River. Moving westward, the path passes south of Princes Island Park and then continues west parallel to Bow Trail.', length: '9269.45', difficulty: 1, coded_path: 'eupvHn}`wTe@?}@JMA[Nm@j@[j@Sp@[tAYzCYdAs@vB_BlG_@x@[XOp@O^q@`CAVo@xBsAhEw@zBDh@{BjGg@dAe@rBGn@oAdFQvCi@jBSjBGrBu@hEOvBMv@YdAWrBWhA_@rAQvAI`@q@fAWLuAfFKRKh@D^E`@oAtEkBjFa@~A]v@]~A?r@F\Er@Hz@@pBN`A@xBMbACzJNvH\`Gr@~IRfBfBnDdBfH|ApDn@lAhCxHT~BRrCrBlERChI~b@l@jB|@vAd@bBZfBZhEHn@Tn@BXC^UvA?jJi@rWMr@?rCDpCJlAEfDSbBAxDUtDG`FMbFRvEx@~CRfA`@l@d@T^\h@zC^~C?jBTvCJjB@xBItCo@nFArAq@zDMfAe@|B}@zDu@tCy@nC{BnGKd@_BbDQLU?}Aq@q@`@s@t@e@lAOj@Kr@aBlI[l@{C~GQt@u@l@k@|AkBbC]t@gB~AeAzDOzIaAzFYxEn@fEqBbLuAvLb@\Bf@Un@_D|W{BhLyDnKyC|HwBnCwAlCmB~Bm@pA}@pA{BbCgAtBy@r@c@dA')




Trail.create!(trail_forks_id: 151936, name: 'River Park to Fort Calgary', description: 'This is part of the City of Calgary"s multi-use pathway system. There are a couple of sections that are shared with cars on quieter residential streets, specifically: Riverdale Avenue SW, 1 block along 26 Ave. SW and the bridge on 25 Ave. SW. The north end of the pathway connects to the Riverwalk and Bow River pathways, providing access to the East Village and Inglewood.
', length: '8829.81', difficulty: 1, coded_path: '}fjvHjujwTaBgBk@kAe@MyErAoE\yBaAu@a@Ie@mAiAgEaUaEsVxBwXg@c@SECOTqA\{Cp@aDToC`@mIAiBy@cIm@iCe@uCW}Bq@}EU_AMw@_@iA_Ay@gAKu@Fw@Za@Vc@f@Yb@SRkApBU|@s@xEM`@G`AKd@Ct@UjBGTa@x@eAdBw@xAa@|@w@`AsArAQVShAa@b@OB_@ZcGfECrEGbAu@Rc@WaBSO?s@QYOu@Ie@Kq@Iq@_@e@a@a@SyBeEGSsAwCsBuJ_@mAM_A?iHB_EVwVMQPiNMk@]Kk@?{Ab@Dc@K}BWDoCz@_AD}GdCmAdAQ~@mAxDe@jGe@LgCoCgAmBy@yBa@}E?iFQeADoCJw@HUOa@JsAp@aAj@i@l@YNYNQhBiB\u@d@i@v@i@^i@n@_@z@gAt@oAl@cBz@oDjBwEZqAX_@l@]Za@j@VDPPCPuAfB}FLgBCkA?eBKkAiAkA_AoAw@Sg@g@yCmBcA]o@i@eADgD^_Dl@cCEc@w@mDc@}Am@Gg@a@k@g@uBmBeCiGuDkCoBeBiBmAoBMa@i@b@_AcA[iAu@cAoCsB{Ag@y@EUGIq@_@YaAc@o@{@oAmAmAfF')


Trail.create!(trail_forks_id: 130002, name: 'Regional Pathway - Nose Creek', description: 'This section of the regional multi-use pathway parallels Deerfoot Trail.', length: '11793.8', difficulty: 1, coded_path: 'kdqvHxo|vTkAFgATmA@}B~@aCb@cCp@uB^iC|@uAl@uCX_Cv@e@ZSv@IbBQn@s@\q@V_@D_BDyFn@u@h@_ASyAdAaAdAiI~FaAl@}B`Eu@^{Br@w@p@uBpAy@bB_CvCs@xAa@l@i@Z[IQ[aAmA[?_@NkHrBg@QkCr@_Bl@yAv@i@l@y@jA_A|@{A^g@Ts@Fc@Ec@F_@Z{@`A_@XYNe@N_AEO@WHQJmAxA[TyGxCkA~@iAnA[~@[r@s@d@}CfDSZ_AbGy@nEQn@OXwBxBe@\aAh@wB~CeArA_KpKkAdA_Ah@y@n@ORIRC^@vEUdDOX[NeDAOQIc@Gy@GYMWQMKAq@J}A~@{@RaAJg@Xg@`@_@He@?y@k@WW_A@YNQBSCQGYBm@ZWR]`@[n@aAzA{A`D_@j@s@h@IJiA`Cc@rAWf@W^s@fBMJmAh@W?w@Um@Bq@b@mBFg@NaAI_@B}@ZwQ`Aw@CYBSJSTOJ[D]?Yk@Sy@a@EQ@u@Nk@FYX[f@Ij@Dt@K^]HWCQGqAFgEnCaBOiA{@sH^s@KYg@q@RUd@mBhBmAZuCIoAm@iAuAm@{Bu@yBaAwAKaE_Ac@gB_@oDg@{AQs@NsBkBaJ`@mBl@yFU}Fc@}CeAiKsC}Ly@kDKcUC{DIuD@{CIwCBqCAgCVgD@qBTuA{@mBI}Fu@MCkDsAWAk@DsAVYLy@LQLqAnAc@RUBwC@eDCkAI[Bi@EqAHm@?iCH_BCc@B]AWFkAMUDaADo@Em@Iq@FaA?SGaCoC_@IQ@q@d@UV')

Trail.create!(trail_forks_id: 6350, name: 'ZC-DT', description: 'A sick trail we built last year with several different lines and hits.', length: '790.067', difficulty: 4, coded_path: 'al{vH|imwTVNLBPYp@o@lAj@h@w@JCl@PLCrAgBHET@JERODMJI`@BLGNA~@LBGFDb@BJDx@k@BGD@JAJMBSDK`@_@To@^q@n@[RGp@M`CHTHfCDb@A')

Trail.create!(trail_forks_id: 46429, name: 'Gerry"s Trail', description: 'A really sweet path', length: '1088.14', difficulty: 3, coded_path: '{e`wHlsrwTlB]XJXIN[`Am@tBi@tDq@jJcCb@Ld@Ep@]hA[b@UlCs@lAoAf@mAx@aGrAwBj@sBV_D')

Trail.create!(trail_forks_id: 46430, name: 'Gerry"s Extension', description: 'a good trail for when you cant get enough', length: '301.522', difficulty: 3, coded_path: '{t~vHvrqwTtBcBv@kAbAm@bAqAv@m@p@I\YL?LE')



Trail.create!(trail_forks_id: 16973, name: 'Sideshow Bob', description: 'Begins with a trail alongside the cliff-face of Bowmont park, then into a short tree section, onto the cliffs again, and finishes through trees to a pathway in the middle of Bowmont park. If you don"t like exposure, this is not the trail for you.', length: '1323.8', difficulty: 4, coded_path: 'utxvH`vxwTUd@e@Pg@HRf@V@LG\_@J?\Ih@JBNJNADg@FmAv@s@Po@h@E?c@l@Od@[ZId@_@|@SPKZMNI?MXYDEFCTUJCVQd@KDS^CJ_@l@g@fC?Jc@f@Oz@ORI\GJET?RIPBLCJYZOZGVML?JWMUDWbAMVC`@UFQ\G?[Ta@rCIlAQh@GFNXHXPRFXLNBLO@EHYtA}BpFWNk@FILYR')

  Trail.create!(trail_forks_id: 42899, name: 'Bowmont Singletrack', description: 'This is a route that follows some of the popular singletrack in Bowmont Park. Following the banks of the Bow River you will be treated to some decent undulating inner city dirt with a few short punchy climbs. This route can be linked up with [L=https://www.trailforks.com/trails/sideshow-bob/]Sideshow Bob[/L] directly to the SE and Twelve Mile Coulee to the NW via a couple km of new paved pathway and tunnels under Stoney Trail. Generally dries out fairly quickly after rain as it is exposed river bank. During winter it can be good fatbiking conditions, and very often rideable on a regular MTB with studs due to walkers and Chinooks. 

Be prepared to yield to dog walkers and oncoming bike traffic, especially on blind corners. 

There is one section near the Silver Springs ravine that does not allow bikes, stick to the upper track, signage is obvious.', length: '3763.32', difficulty: 3, coded_path: 'qf|vH~maxTRDFLLf@IfCBFP@PARYx@c@Tm@FYB_@DDBJJCl@y@Fs@@i@XwBAWUu@?c@l@wB\qC?MOgAIaB?s@P_AJqA?s@N_C@iADSPMPUj@i@ZG@UBGd@g@r@aADa@CWKQ_Ao@u@]OQKUG_A@W|@gAFS?WYoCKMc@U]e@CM?YHmAHSFCNBh@AVI`Ac@Xa@b@cAR]BO@q@Jw@CUOi@Fo@b@gAp@iAVq@Je@Tq@?[Ge@@g@Aa@DERCFEl@w@LYT}@^k@?KI@y@`@KL]n@y@`@GCAIBaAQi@Q]OMgBk@oAm@WQQUc@]Um@G_@Ae@Ds@BKNSVAFDNN@f@HZb@x@HJf@Rf@Zj@DHCV@NC`ACRFF?ZM^]Zg@Vq@FGl@QP?NCFGF[FKP?d@G`@JF?VKFGPq@l@c@HKXo@d@}AJITc@LK\IDKDk@Ni@Do@AOOo@?MDUPa@NQl@a@HKDOBk@BI|@{Ar@g@\g@XMVShB_CJIVe@JGLSHg@Ri@TOJO`@yATa@F_@NU\cAH[B[FMRUBM?]Zw@VmAZa@n@uAPQRa@`@g@Zs@P_ALWN?DEFo@JILm@B]To@')

  Trail.create!(trail_forks_id: 66336, name: 'CMBA Link', description: 'Built in 2016 by the Calgary Mountain Bike Alliance, this trail connects the Bowmont Single Track and [L=https://www.trailforks.com/trails/sideshow-bob/]Sideshow Bob[/L]. This is a reroute of existing trail, which can no longer be accessed due to a new storm water drainage system being built by the city.', length: '759.047', difficulty: 3, coded_path: '{wyvHl{zwTEh@Md@GLURUFq@F[GQMe@UGIQk@i@gC[i@MIo@IKEEBK^@JTJPPZl@T|@Z~@JbALj@DJHFLRJ`@JPBTYv@?TTPnAZR?RKJ??j@MhAEPa@r@WVELLv@VRFR')

  Trail.create!(trail_forks_id: 102817, name: 'Edgemont Ravine', description: 'Paved pathway', length: '3413.07', difficulty: 1, coded_path: 'ey`wHl_vwTHJJF`AVH?FDPf@@|ASx@IbAMNG@i@@_@Ce@Nu@h@]b@K`@CVQ^mAxA[V}@FYFk@h@KDILI\Yh@a@Xa@L[E_@Qm@OsAk@OOWg@]sAS[OKe@OuAcAq@]c@[c@K_@?k@Es@LWCYO_@o@Y[o@c@]i@Qg@k@{FGSa@gCc@oAUW_@OWEc@FOC{@a@c@k@oAaD?sBX}A@OCy@@iAB_@^yABUH_DLiCA_@PkE?w@Gu@EUa@{@Qm@Y_BAYBq@Hq@@sB\sBAk@S{A[gAy@qBy@yA_@mASqASwDa@mBYo@u@sAi@kACUAeAGk@_@}A_@qBWgBM{ACs@FwAH{@AKQU[QKMEQG}@DaAHq@T_ALw@@WASKm@_@y@Mk@GcFGwAQaBGaAAqBEk@Ke@Sk@{@oACIBQ')

  Trail.create!(trail_forks_id: 102824, name: 'Edgevalley Connector', description: '', length: '164.947', difficulty: 3, coded_path: 'mxawH~otwT@FMz@GdADfBA|BG`B')

  Trail.create!(trail_forks_id: 108617, name: 'South Ridge Extension', description: '', length: '204.875', difficulty: 3, coded_path: 'kc|vH|jqwTXWDAP[JmAXo@Vu@ZwARoAFy@H_@')

  Trail.create!(trail_forks_id: 8244, name: '12 Mile Coulee', description: 'The 12 Mile Coulee area is in the community of Tuscany, in Calgary"s NW.  There are trails on both sides of the creek that runs down the coulee, and there are many crossings, most without any kind of bridge.  For the most part it"s old school narrow XC singletrack.  Other than a couple of short and steep climbs, it"s not overly strenuous.  Be aware that close to 90% of trail users are walkers and runners, often with little kids or dogs in tow.  There are some sections of trail that have blind corners, so be prepared to dump speed and yield the trail.', length: '2865.96', difficulty: 4, coded_path: 'qj`wH`vgxTQ}@R{@H_A?QGY?qAHm@?[CsAD[^g@FAPOJEPSTq@Nq@XsBBCH?POn@y@FEl@Cz@BTCNIB?`At@NDj@M`@c@N]^UPGZV\BBD\?VW?IJe@z@mB\Il@Gf@AVCfALr@CTULSp@q@NGR?^LTCBEP?PF`AYJ@b@P\j@j@p@J@ZGf@k@ZPZHLFl@DNEN@JJv@j@f@CFCLKBGVcBFkAj@yBZa@J?TDn@UHIh@eBDi@BMTMHARKPC@ETEHGRYFQ\S\a@hAgBZQ`@w@Vy@VYN]NMLIRyAN_@NSPGLAJG`@kCLWZKXLLENHNLJBNEtAw@NCn@c@fAc@H@RQp@_@PQ^MRk@N?ZY@GNQJSLKHKNi@`@k@Nk@NCNJR\DL^RJ@JGJJBAPLn@pADRLZf@n@c@dAGXINGTgAx@c@`@eA|BSZ')

    Trail.create!(trail_forks_id: 33743, name: 'Tuscany Bluff', description: 'Dry trail away from the creek in 12 Mile Coulee. Good sightlines, but keep an eye out for dogs, as this trail gets close to the off-leash zones.', length: '2056.64', difficulty: 4, coded_path: 'yv_wHpxfxTQ[KaACG@g@CmCI]M{ASs@Gi@IWPBJJZJNAjABp@AhDJfAGPJV^p@H`@NP@TNt@fAv@t@FNDSAQVUXm@RYv@i@RIr@M|@BVa@n@BhACrBaBNSnA_AZa@FUd@oBF{@Lm@r@cAj@k@l@yAx@wAZu@T_AR[Na@h@i@hBuDXa@PIXGz@CX@zAXb@DDDd@BRDt@?NQHQJg@^mDJMLILAnBb@f@BdACvBe@z@D')
  
    Trail.create!(trail_forks_id: 100410, name: 'Lose Yourself', description: 'Part of the 12 Mile Couly area in the community of Tuscany, in Calgary"s NW.    This trail is South facing and runs East - West along the the old Bow River valley slopes similar to the Bowmont Singletrack.   The route follows the cliff side and has some  roller coasters on the west end of the trail.     Because the trail is South facing it tends to dry out earlier in the spring and is a little warmer in the fall.   Combining this trail with the [L=https://www.trailforks.com/trails/12-mile-coulee/] 12 mile coulee[/L] creates a nice out and back circuit after work or when you"re looking to fit in a quick single track ride.', length: '1092.58', difficulty: 4, coded_path: 'e||vH~hexT@G@HALAnAFj@B`DBv@Ll@GnBD`A?n@@r@Iz@Hf@Bt@MnBUxACjAGv@AlBHjBCxBCNYt@Id@EVClAEJMLADGpA@x@Ar@G|@QxAWvAc@h@[vAm@~DQv@UlBWfAGrAIh@KlA')

    Trail.create!(trail_forks_id: 3404, name: 'Burnt Forest', description: 'Loose rocks, technical uphill, river traverses and rocky downhill sections', length: '16091.5', difficulty: 5, coded_path: 'k{cnF_{x_DRxAWz@_@v@u@|Bk@~@[~@Y`@uDdJ[rAMpAQG_@RsAVo@VW?[VC?Y\@FOEUHQ\?ZUBCL_@JOLc@nBW^Tn@CdATbBZjA`@VNVFt@Td@[|APz@Bd@OxA?nAg@rF?n@Ux@[j@Qn@It@SXCd@W|@KHECKFOBQIS@WG?FOCOFMAQF[UIBw@c@a@KCKF[MKYs@OIO[N_@l@AjAWlAc@l@i@hA_CZeBAIa@WQe@q@^w@D_@_@[CUUq@MaAk@UA_Au@_@GwBgBQD[YUCGH_@]UAa@QSPc@OoAq@i@MK@u@Q}@k@c@Im@FKYBa@k@iCY@i@MaAzBkBhBYRiB~Bg@jAK^KzAo@~AAHThA@^UCMHFB?DAC[`Bi@fBI|AUx@k@l@IZ[Vw@VcAr@gAj@]F_Ah@YFuAv@YD_@Po@b@aAZe@FY@w@i@WGi@_@o@oAi@]Wm@M_Ai@q@uAq@eA]SCu@g@]E_@Os@Im@Us@Mw@s@c@mA_@B_@SM]Is@q@eAAk@o@eASs@_@_@]s@Gk@k@qA]aCWy@OQo@a@_AgBsCoCSI]@aAWsADc@f@]Nk@Iq@Wu@Fs@EkCFkBb@y@B_@FgAf@yAJoAV]Aw@c@e@EG@s@Xm@^]Hy@x@{Af@a@d@g@VgAfAcCf@aGRkBb@cBfAg@PgDlBy@p@w@Zo@LyAp@y@z@a@R_BhAMDa@EC@]h@WE_DGrB{D?E_@aAc@eBQYu@q@EKGoAXaCZsATgBNe@@iBTeBEK?wAVq@Me@Lc@Go@^aDJeC@cCV}@@mAe@eBEa@J]Fq@I_ASo@YsDOcAFk@ScAK_Ce@kC?OgAsFk@mBQmB[eAQYEm@Wg@WoAeAeDK}@@]TcADq@Ew@Pu@bCcD~@oBdB_Cz@{@t@Yv@aABY`@K~@eAHUAc@Pa@RM\NZMr@s@b@UHBjAkALARo@z@q@nB_DDBAEr@gANEx@o@z@y@PCf@W^GRBf@a@j@Iv@YZa@h@SB?tElF^r@l@fBr@|@~Bv@j@F~AHnAQpCeBpBy@b@Yh@y@j@}BDIhAyAv@wA^a@v@]bBa@n@IvCF`AQz@e@`@e@h@y@`@QPy@V]fBaE~BaEPH`@h@h@hBh@f@nA`@hETfAPh@?dGXvAYtA{@b@OdB_@xAE`@FbAf@pAG~BzA`@x@Ln@B`@GhADlB^zBCh@Hv@@dANnANlCW`AU^a@ZMZ?HFdANd@PfArAlDlEvFpA`E^n@pAn@p@BfBXdAh@n@Pv@Ap@HVPd@r@VlAFrDj@rBdAlBp@j@v@vBj@~DB|Aj@dBTd@VRPd@VxBf@hAp@vCf@y@bAwC`@F~@n@LDX\FXpBh@l@BNEnABrAShBIb@@h@Ov@e@p@Gf@RX\Zl@`@lADzAQlBBTFBH?rAu@jAc@jAq@LEVg@j@oDtBoEf@c@hAe@l@IhB|@nC~@VLFLy@n@c@f@sAp@i@`@_A|AYx@Mf@')

    Trail.create!(trail_forks_id: 3405, name: 'Pigi-Agios Charalampos', description: 'Mixed trail. Paved and loose dirt sections', length: '8704.77', difficulty: 4, coded_path: 'evcnF{pf`Dm@WGIOu@ICIFQWMEGT?IK?a@hAo@nAGRk@j@Ol@e@t@_Av@i@HWrBOVOD_@\_@f@UHM?UUe@IQHSTK\J`@C~@FXBf@GROBWGURg@vAI@QO]MUBEDKBIII?yD~@u@Cg@D}@f@wAj@]Rc@b@BBSDALkAj@?HKM[HkAnAIRg@\C?g@bDK?WRc@nAQtABrBRn@Ah@k@z@GAS|@c@bAw@v@SXMZWb@O`@wAbBq@T[Vo@p@O\SXeAdAMVSL{@fA[B_@MU?[VgAf@k@LiA@}@La@Nc@HmAO{@Bs@^QPmAM[I_Am@So@KSQAg@H_BDYNo@j@SViBxAI@iAOSBQH}AdAk@|@?HkAPo@TeA?SI}@?SBo@VI?O]SG]Ac@RS?SDW?ICYSQAYk@oAeAk@w@m@k@M]IIOIc@?SDQ?g@Oo@q@KCw@gAEMSOG?c@e@]OO]MIk@?kAY}AIc@Ng@HIHK?o@j@WDIRi@j@]h@IBi@rAUNWXeAfBaAt@ECwAbB]Ns@B_@NuAbAi@N{@t@If@KX}@\c@f@M?YHSRYDMHe@BWH_@Vg@DsBdAQDYPu@Nq@Xs@F[?]MW?YMi@g@mCHkAj@IN?\KVg@?MCIROAQXIDI?c@z@CLq@p@AXJd@FHC\MREf@I@NxAPPJl@PRNDHPj@b@j@RPB|ASL?\QRB\MPAjAJbAEPBTR?`AH`@`@Ct@WTAd@a@hD_Bf@QXHZEDBJ?\SbAG@ERDLIL?JKZ@XST_@ZMFBf@Wb@I|@]t@k@b@Ff@tAZ\\HRLnApA|Ad@XNL?j@JZj@XTn@RbAp@h@PXDTNPAb@^Z`@?LDCZLP?LHl@HVMZDPLHLPIvAh@pAAjANXR\?tAa@VAVHVRdATdAOn@W^{ANoAHwAj@aDHeADyA?mADA\\PDd@Eh@MdBMTIb@?HPJ?Fq@Gk@FI\`@NJj@PRJRBVEFWO_ABUNHBRHCl@cAC_@OiAB{@Kw@B_APYX}AdAqAL_AJYZGRIp@?TKp@JLAJG|@FJGVBv@M?BRoAz@cBH}ANKJ?')
  
    Trail.create!(trail_forks_id: 3408, name: 'Agia Marina-Kormi', description: 'Uphill double track and rocky downhill single track', length: '6408.6', difficulty: 4, coded_path: 'uugmFobfaDP?PDFAl@SFOZETJR?XXN@`@K`@Wp@RTAPU?K\St@Qv@g@\IPM^?FIB?tA|@jBj@PVl@IVFhAM`A@rAj@KPAhAZz@?^XlBNPAHXHDLXVb@NBNZ`@Ll@Bl@DB?XZZLl@z@z@Nj@^j@^`Af@\?^QpAITYVk@H[Qs@Ie@k@k@MaB^VTsADyBr@]B]]gAc@IKI[A}AQ_A}@{A_@UUCgAAiC|@WDoA@g@^c@x@KF@HE?cBuBk@kB_@y@{@oCa@[_@e@e@?IKHKASPYJi@ESMAW]Ks@NoDZaBDk@Kk@II]AoALg@RICUe@w@iA[wAy@sBUMI@eA`@O?sAW[Q]y@c@s@OMg@G_@NEAU_AIEaAQqEqCmAnBy@`BEBqAGWVCFYHkAfBUp@c@d@gAyAM?URQA[q@WS[EEBB@ABQCOU]M]COHe@AyBb@e@h@E?Ub@EM@FIXMTSHMIQw@Sa@De@Se@KIUHCYYKw@@o@NmAJaA[e@@MHWGYDqAbBgBv@GFe@|@e@l@]Jy@OI@g@LMXaCJyAp@}@rAQzAg@fAa@?q@Sc@@a@Wa@@a@IEH}@Zi@`@e@PqA~@u@jAMl@w@|@{A\g@XIJW~@m@xEa@|@aAzAmApDMzBJd@^l@CRCDMDu@AyAO{A_@c@@gBZUWQu@Ys@}BiA_BsAeA[G?oCmA')

    Trail.create!(trail_forks_id: 16459, name: 'Fuzzy Groover', description: '', length: '534.445', difficulty: 4, coded_path: 'mgyuHl|rwTk@o@[gAM?KCSHc@r@{@dBs@nBmAT{@Hw@PSf@WpBGPSF]d@Oj@a@PUHQVWLw@t@')

    Trail.create!(trail_forks_id: 16511, name: 'Votier"s Flats Riverside', description: 'Green singletrack has a few roots and rocks, but nothing major. Connects Votier"s Flats and Bridge 7.', length: '1055.11', difficulty: 3, coded_path: 'ka{uHbrkwT^kAFa@TUd@\ZyA@k@B]Xy@Jc@DG?Sr@MFQ@SEQGEj@SHIVDt@KDEd@iC@aABm@?_BCq@Sc@Ta@Ac@W{@o@iAQBOUOAe@i@YNGEUm@DO?MQEGE?Sa@KMcASE[mBUw@Ye@Rk@XgBTk@H]A[WgBAU_A{B')

    
User.create!(name: "Cristof")

Rating.create!(feedback: 3, trails_id: 1, users_id: 1)

Comment.create!(data: "Pretty nice could use some work", trails_id: 1, name: 'Thomas')
Comment.create!(data: "Pretty nice could use some work", trails_id: 2, name: 'Thomas')

TrailSolution.create!(description_to_fix: "SO MANY TREE'S", timeline_days: 10, cost: 250, collaboration: "myself", trails_id: 1, users_id: 1)
